# This file was automaticassetIndx
# ally generated by scripts/regen-py.pl at 20190828-043424
# applies JSON schema to generate Deriv API
#
# =======================
# ----- API Methods -----
# =======================

class DerivAPICalls:
    # To be implemented by the sub-class
    # __init__

    def accountClosure(self, args = {}):
        """
        @param {Object} args
        @param {Number} args.account_closure - Must be `1`
        @param {Any} args.passthrough - [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
        @param {String} args.reason - Reason for closing off accounts.
        @param {Number} args.req_id - [Optional] Used to map request to response.
     
        """
        config = {
            "account_closure": {
                "required": 1,
                "type"    : "numeric",
            },
            "passthrough": {},
            "reason"     : {
                "required": 1,
                'type'    : 'string',
            },
            'req_id': {
                'type': 'numeric',
            },
        }

        allArgs = {
            'method'        : 'account_closure',
            'needsMethodArg': '1',
            'args' : args,
            'config' : config
        }

        return self.processRequest(allArgs)

    def processRequest(self, allArgs):
        pass